# Generated by Django 5.1.1 on 2026-05-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='weather',
            field=models.CharField(choices=[('Cloudy', 'Cloudy'), ('Rainy', 'Rainy'), ('Sunny', 'Sunny'), ('Windy', 'Windy')], default='Sunny', max_length=20),
        ),
    ]
